### PR TITLE
fix failing to build iOS workspaces with multiple apps

### LINKED ISSUE #1230: Can't build for xcode -- multiple projects
**Description**
Can't run Radon because of multiple project files found:
```
2025-06-06 21:45:04.425 [warning] Found multiple XCode workspace files: file:///Users/matthewaherz/Documents/Work/MyLineupInk/App/my-lineup/ios/.spm.pods/packages/.umbrella/.build/checkouts/MyLineupInkCore/.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata, file:///Users/matthewaherz/Documents/Work/MyLineupInk/App/my-lineup/ios/mylineup.xcworkspace/contents.xcworkspacedata
2025-06-06 21:45:04.454 [warning] Found multiple XCode project files: file:///Users/matthewaherz/Documents/Work/MyLineupInk/App/my-lineup/ios/MyLineupInkWidgetFramework/MyLineupInkWidgetFramework.xcodeproj/project.pbxproj, file:///Users/matthewaherz/Documents/Work/MyLineupInk/App/my-lineup/ios/MyLineupInkWidgetFramework/SampleProject/SampleProject.xcodeproj/project.pbxproj
2025-06-06 21:45:04.454 [info] [Reload] Could not find Xcode project files in "/Users/matthewaherz/Documents/Work/MyLineupInk/App/my-lineup/ios" folder. Verify the iOS project is set up correctly.
2025-06-06 21:45:04.454 [error] Error: Could not find Xcode project files in "/Users/matthewaherz/Documents/Work/MyLineupInk/App/my-lineup/ios" folder. Verify the iOS project is set up correctly.
    at buildApp (/Users/matthewaherz/.vscode/extensions/swmansion.react-native-ide-1.7.1-darwin-arm64/dist/extension.js:364374:15) Failed to perform reload action autoReload
2025-06-06 21:45:04.459 [error] Error: Could not find Xcode project files in "/Users/matthewaherz/Documents/Work/MyLineupInk/App/my-lineup/ios" folder. Verify the iOS project is set up correctly.
    at ul (https://file+.vscode-resource.vscode-cdn.net/Users/matthewaherz/.vscode/extensions/swmansion.react-native-ide-1.7.1-darwin-arm64/dist/panel.js:1:760) [WEBVIEW LOG] Uncaught promise rejection
2025-06-06 21:45:04.459 [error] [WEBVIEW LOG] Uncaught exception Error: Could not find Xcode project files in "/Users/matthewaherz/Documents/Work/MyLineupInk/App/my-lineup/ios" folder. Verify the iOS project is set up correctly.
    at ul (https://file+.vscode-resource.vscode-cdn.net/Users/matthewaherz/.vscode/extensions/swmansion.react-native-ide-1.7.1-darwin-arm64/dist/panel.js:1:760)
2025-06-06 22:02:40.672 [info] Disposing IDE instance
```

When I run searching for the projects or workspaces I get my framework and sample projects too:
` ➜  my-lineup git:(main) ✗ find . -name "*.xcodeproj" -o -name "*.xcworkspace" | grep -v './node_modules'`
```
./ios/MyLineupInkCore/.swiftpm/xcode/package.xcworkspace
./ios/mylineup.xcodeproj
./ios/mylineup.xcodeproj/project.xcworkspace
./ios/Pods/Pods.xcodeproj
./ios/MyLineupInkWidgetFramework/SampleProject/SampleProject.xcodeproj
./ios/MyLineupInkWidgetFramework/SampleProject/SampleProject.xcodeproj/project.xcworkspace
./ios/MyLineupInkWidgetFramework/MyLineupInkWidgetFramework.xcodeproj
./ios/MyLineupInkWidgetFramework/MyLineupInkWidgetFramework.xcodeproj/project.xcworkspace
./ios/mylineup.xcworkspace
```

Could we allow specifying the exact workspace/xcodeproj?

**Environment**

Mac OS, vscode
- Version of currently used Radon IDE: 1.7.1
- Version of React Native/Expo used in the project. 18.3.1, 52.0.46
- Any other versions of tools related to the problem.

### PR DESCRIPTION
**Pull request by jwajgelt**
Allows Radon to build iOS apps with mulitple xcode projects present in the `ios` directory.

We change the logic for picking the xcode project/workspace to pass to xcode build to use `react-native-cli` package to ensure we're able to build and run apps that regular `npm run ios` would handle.

Fixes #1230

### How Has This Been Tested: 
- open a (non-expo) RN workspace in XCode
- add a project to the workspace and put it inside the `ios` directory
- open the same project in Radon
- it should build

### CODE REVIEW

File: packages/vscode-extension/src/utilities/xcode.ts [hunk 1]
```diff
@@ -1,92 +1,56 @@
...
-  } else if (xcodeprojFiles.length >= 1) {
-    xcodeprojLocation = getParentDirectory(xcodeprojFiles[0]);
-  }
-
-  if (xcodeprojLocation) {
+export function findXcodeProject(appRootFolder: string): IOSProjectInfo | null {
+  try {
+    const projectConfig = getIOSProjectConfig(appRootFolder, { sourceDir: "ios" });
+    if (!projectConfig || !projectConfig.xcodeProject) {
+      return null;
```
Comment (filip131311) [inline packages/vscode-extension/src/utilities/xcode.ts:41]: can you add telemetry here? I belive this is a good change but I am worried that the CLI behavior will be diffrent enough to cause some regresions and would like to control that for few versions

Comment (jwajgelt) [reply packages/vscode-extension/src/utilities/xcode.ts:41]: Since we didn't track this before, you won't catch any regressions here, or rather you won't be able to tell them apart from projects that are simply misconfigured (and don't work anywhere).
The only case where this could cause a regression compared to the previous approach we had, is if someone already only uses XCode to build the native app (without either `rn-cli` or `expo-cli`, since the method we use here should handle setups compatible with them), _and_ have only a single project in their `ios` directory (since we'd reject them previously anyway in that case).

Comment (jwajgelt) [reply packages/vscode-extension/src/utilities/xcode.ts:41]: Added.
