### PR TITLE
Fix failing to obtain $PATH 

### LINKED ISSUE #896: Paid for 1 year but still lots of issues, no IOS devices found, NPM ENAMETOOLONG (output)
**Description**
I paid for 1 year because I thought it might be an issue with my license as I was one of the first beta testers.

I am using Cursor IDE.

Firstly, I have installed node via MISE, I was using NVM before but I could never get it to work, and I saw a message saying MISE was supported.,

```
which node
/Users/ian/.local/share/mise/installs/node/23.6.0/bin/node

which npm
/Users/ian/.local/share/mise/installs/node/23.6.0/bin/npm
```

```
node --version
v23.6.0

npm --version
10.9.2
```

IOS simulators do not show the correct  simulators, seems they are not connected or something ?
My code is on iPhone 16 not 15

CleanShot 2025-01-13 at 06 16 55@2x

CleanShot 2025-01-13 at 06 17 26@2x

CleanShot 2025-01-13 at 06 22 37@2x

CleanShot 2025-01-13 at 06 23 54@2x

CleanShot 2025-01-13 at 06 25 18@2x

Also, under OUTPUT for RADON IDE, I have the following, which is probably why the above is not working

```
2025-01-13 06:20:26.995 [info] Found app root folder: /Users/ian/Development/sandbox/expo_test/StickerSmash
2025-01-13 06:20:42.623 [info] Launching devtools
2025-01-13 06:20:42.623 [info] Launching metro
2025-01-13 06:20:42.625 [info] Devtools started on port 50740
2025-01-13 06:20:42.632 [error] Error: Command failed with ENAMETOOLONG: npm --version
spawn ENAMETOOLONG
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:776:9)
	at A5 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:14:9974)
	at w6.exports.command (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:14:11650)
	at zp (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:139:2977)
	at TO (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:158:11071)
	at async I9.getPackageManager (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:4698)
	at async I9.checkNodeModulesInstallationStatus (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:5948)
	at async t.maybeInstallNodeModules (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:161:29511)
	at async Promise.all (index 1)
	at async Xv.startInternal (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:161:4695) Command npm --version execution resulted in an error:
2025-01-13 06:20:42.632 [error] Required package manager: npm is not installed
2025-01-13 06:20:42.632 [info] Installing node modules
2025-01-13 06:20:42.649 [error] Error: Command failed with ENAMETOOLONG: npm --version
spawn ENAMETOOLONG
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:776:9)
	at A5 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:14:9974)
	at w6.exports.command (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:14:11650)
	at zp (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:139:2977)
	at TO (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:158:11071)
	at async I9.getPackageManager (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:4698)
	at async I9.installNodeModules (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:3745)
	at async t.maybeInstallNodeModules (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:161:29667)
	at async Promise.all (index 1)
	at async Xv.startInternal (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:161:4695) Command npm --version execution resulted in an error:
2025-01-13 06:20:42.649 [error] Required package manager: npm is not installed
2025-01-13 06:20:42.649 [info] Installing node modules succeeded
2025-01-13 06:20:42.653 [error] Error: Command failed with ENAMETOOLONG: node /Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/lib/expo_start.js
spawn ENAMETOOLONG
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:776:9)
	at A5 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:14:9974)
	at St (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:139:2548)
	at Xv.launchExpoMetro (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:161:4213)
	at Xv.startInternal (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:161:5178) Metro exited unexpectedly
2025-01-13 06:20:42.653 [error] Error: Command failed with ENAMETOOLONG: node /Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/lib/expo_start.js
spawn ENAMETOOLONG
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:776:9)
	at A5 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:14:9974)
	at St (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:139:2548)
	at Xv.launchExpoMetro (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:161:4213)
	at Xv.startInternal (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:161:5178) Subprocess node /Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/lib/expo_start.js execution resulted in an error:
2025-01-13 06:20:42.653 [error] Error: Child process doesn't have stdout
	at gl (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:139:2256)
	at /Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:161:5473
	at new Promise (<anonymous>)
	at Xv.startInternal (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:161:5252) Unhandled promise rejection
2025-01-13 06:20:42.653 [error] Error: Child process doesn't have stdout
	at gl (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:139:2256)
	at /Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:161:5473
	at new Promise (<anonymous>)
	at Xv.startInternal (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:161:5252) Unhandled promise rejection
2025-01-13 06:20:42.816 [error] Error: Command failed with ENAMETOOLONG: node /Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/lib/expo_go_project_tester.js
spawn ENAMETOOLONG
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:776:9)
	at A5 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:14:9974)
	at St (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:139:2548)
	at L6 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:150:6060)
	at N9 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:7472)
	at I9.checkAndroidDirectoryExits (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:2997)
	at I9.runAllDependencyChecks (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:2415)
	at E4.handleRemoteCall (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:162:8294)
	at a.value (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:162:7628)
	at o.B (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:734)
	at o.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:951)
	at g.$onMessage (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:182:32440)
	at R.S (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:5985)
	at R.Q (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:5751)
	at R.M (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:4772)
	at R.L (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:3825)
	at a.value (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:2299)
	at o.B (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:734)
	at o.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:951)
	at u.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:133:14600)
	at a.value (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:213:8663)
	at o.B (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:734)
	at o.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:951)
	at u.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:133:14600)
	at MessagePortMain.<anonymous> (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:213:6789)
	at MessagePortMain.emit (node:events:519:28)
	at MessagePortMain.emit (node:domain:488:12)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2619) Subprocess node /Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/lib/expo_go_project_tester.js execution resulted in an error:
2025-01-13 06:20:42.816 [error] Error: Command failed with ENAMETOOLONG: node /Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/lib/expo_go_project_tester.js
spawn ENAMETOOLONG
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:776:9)
	at A5 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:14:9974)
	at St (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:139:2548)
	at L6 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:150:6060)
	at N9 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:7472)
	at I9.checkIOSDirectoryExists (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:3251)
	at I9.runAllDependencyChecks (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:2503)
	at E4.handleRemoteCall (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:162:8294)
	at a.value (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:162:7628)
	at o.B (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:734)
	at o.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:951)
	at g.$onMessage (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:182:32440)
	at R.S (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:5985)
	at R.Q (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:5751)
	at R.M (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:4772)
	at R.L (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:3825)
	at a.value (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:2299)
	at o.B (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:734)
	at o.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:951)
	at u.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:133:14600)
	at a.value (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:213:8663)
	at o.B (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:734)
	at o.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:951)
	at u.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:133:14600)
	at MessagePortMain.<anonymous> (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:213:6789)
	at MessagePortMain.emit (node:events:519:28)
	at MessagePortMain.emit (node:domain:488:12)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2619) Subprocess node /Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/lib/expo_go_project_tester.js execution resulted in an error:
2025-01-13 06:20:42.816 [error] Error: Command failed with ENAMETOOLONG: node /Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/lib/expo_go_project_tester.js
spawn ENAMETOOLONG
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:776:9)
	at A5 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:14:9974)
	at St (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:139:2548)
	at L6 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:150:6060)
	at N9 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:7472)
	at I9.checkPodsInstallationStatus (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:6218)
	at I9.runAllDependencyChecks (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:2564)
	at E4.handleRemoteCall (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:162:8294)
	at a.value (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:162:7628)
	at o.B (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:734)
	at o.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:951)
	at g.$onMessage (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:182:32440)
	at R.S (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:5985)
	at R.Q (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:5751)
	at R.M (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:4772)
	at R.L (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:3825)
	at a.value (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:2299)
	at o.B (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:734)
	at o.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:951)
	at u.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:133:14600)
	at a.value (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:213:8663)
	at o.B (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:734)
	at o.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:951)
	at u.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:133:14600)
	at MessagePortMain.<anonymous> (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:213:6789)
	at MessagePortMain.emit (node:events:519:28)
	at MessagePortMain.emit (node:domain:488:12)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2619) Subprocess node /Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/lib/expo_go_project_tester.js execution resulted in an error:
2025-01-13 06:20:42.820 [error] Error: Command failed with ENAMETOOLONG: xcrun simctl list runtimes --json
spawn ENAMETOOLONG
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:776:9)
	at A5 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:14:9974)
	at St (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:139:2548)
	at P9 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:7616)
	at R9.listInstalledIOSRuntimes (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:16668)
	at E4.handleRemoteCall (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:162:8294)
	at a.value (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:162:7628)
	at o.B (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:734)
	at o.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:951)
	at g.$onMessage (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:182:32440)
	at R.S (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:5985)
	at R.Q (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:5751)
	at R.M (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:4772)
	at R.L (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:3825)
	at a.value (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:2299)
	at o.B (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:734)
	at o.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:951)
	at u.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:133:14600)
	at a.value (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:213:8663)
	at o.B (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:734)
	at o.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:951)
	at u.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:133:14600)
	at MessagePortMain.<anonymous> (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:213:6789)
	at MessagePortMain.emit (node:events:519:28)
	at MessagePortMain.emit (node:domain:488:12)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2619) Subprocess xcrun simctl list runtimes --json execution resulted in an error:
2025-01-13 06:20:42.825 [error] Error: Command failed with ENAMETOOLONG: npm --version
spawn ENAMETOOLONG
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:776:9)
	at A5 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:14:9974)
	at w6.exports.command (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:14:11650)
	at zp (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:139:2977)
	at TO (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:158:11071)
	at async I9.getPackageManager (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:4698)
	at async I9.checkPackageManagerInstallationStatus (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:5758) Command npm --version execution resulted in an error:
2025-01-13 06:20:42.826 [error] Required package manager: npm is not installed
2025-01-13 06:20:42.829 [error] Error: Command failed with ENAMETOOLONG: npm --version
spawn ENAMETOOLONG
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:776:9)
	at A5 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:14:9974)
	at w6.exports.command (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:14:11650)
	at zp (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:139:2977)
	at TO (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:158:11071)
	at async I9.getPackageManager (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:4698)
	at async I9.checkNodeModulesInstallationStatus (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:5948) Command npm --version execution resulted in an error:
2025-01-13 06:20:42.829 [error] Required package manager: npm is not installed
2025-01-13 06:20:42.838 [error] Error: Command failed with ENAMETOOLONG: xcrun simctl list runtimes --json
spawn ENAMETOOLONG
    at ux (https://file+.vscode-resource.vscode-cdn.net/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/webview.js:1583:20981) [WEBVIEW LOG] Uncaught promise rejection
2025-01-13 06:20:42.839 [error] [WEBVIEW LOG] Uncaught exception Error: Command failed with ENAMETOOLONG: xcrun simctl list runtimes --json
spawn ENAMETOOLONG
    at ux (https://file+.vscode-resource.vscode-cdn.net/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/webview.js:1583:20981)
2025-01-13 06:20:42.852 [info] Could not find Xcode project files in "/Users/ian/Development/sandbox/expo_test/StickerSmash/ios" folder
2025-01-13 06:20:43.543 [error] Error: Command failed with ENAMETOOLONG: xcrun simctl --set /Users/ian/Library/Caches/com.swmansion.radon-ide/Devices/iOS list devices --json
spawn ENAMETOOLONG
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:776:9)
	at A5 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:14:9974)
	at St (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:139:2548)
	at oy (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:13770)
	at sy (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:13975)
	at R9.loadDevicesInternal (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:16410)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5) Subprocess xcrun simctl --set /Users/ian/Library/Caches/com.swmansion.radon-ide/Devices/iOS list devices --json execution resulted in an error:
2025-01-13 06:20:43.545 [error] Error: Command failed with ENAMETOOLONG: xcrun simctl --set /Users/ian/Library/Caches/com.swmansion.react-native-ide/Devices/iOS list devices --json
spawn ENAMETOOLONG
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:776:9)
	at A5 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:14:9974)
	at St (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:139:2548)
	at oy (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:13770)
	at sy (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:14000)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Promise.all (index 1)
	at async R9.loadDevicesInternal (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:16496) Subprocess xcrun simctl --set /Users/ian/Library/Caches/com.swmansion.react-native-ide/Devices/iOS list devices --json execution resulted in an error:
2025-01-13 06:20:43.546 [error] Error: Command failed with ENAMETOOLONG: xcrun simctl list runtimes --json
spawn ENAMETOOLONG
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:776:9)
	at A5 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:14:9974)
	at St (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:139:2548)
	at P9 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:7616)
	at sy (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:14050)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Promise.all (index 1)
	at async R9.loadDevicesInternal (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:16496) Subprocess xcrun simctl list runtimes --json execution resulted in an error:
2025-01-13 06:20:43.546 [error] Error: Command failed with ENAMETOOLONG: xcrun simctl list runtimes --json
spawn ENAMETOOLONG
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:776:9)
	at A5 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:14:9974)
	at St (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:139:2548)
	at P9 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:7616)
	at sy (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:14050)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Promise.all (index 1)
	at async R9.loadDevicesInternal (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:16496) Error fetching simulators
2025-01-13 06:20:44.020 [error] Error: Command failed with ENAMETOOLONG: node /Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/lib/expo_go_project_tester.js
spawn ENAMETOOLONG
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:776:9)
	at A5 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:14:9974)
	at St (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:139:2548)
	at L6 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:150:6060)
	at N9 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:7472)
	at I9.checkPodsCommandStatus (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:5565)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5) Subprocess node /Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/lib/expo_go_project_tester.js execution resulted in an error:
2025-01-13 06:20:45.993 [error] Error: Command failed with ENAMETOOLONG: xcrun simctl list runtimes --json
spawn ENAMETOOLONG
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:776:9)
	at A5 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:14:9974)
	at St (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:139:2548)
	at P9 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:7616)
	at R9.listInstalledIOSRuntimes (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:16668)
	at E4.handleRemoteCall (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:162:8294)
	at a.value (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:162:7628)
	at o.B (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:734)
	at o.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:951)
	at g.$onMessage (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:182:32440)
	at R.S (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:5985)
	at R.Q (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:5751)
	at R.M (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:4772)
	at R.L (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:3825)
	at a.value (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:187:2299)
	at o.B (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:734)
	at o.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:951)
	at u.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:133:14600)
	at a.value (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:213:8663)
	at o.B (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:734)
	at o.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:951)
	at u.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:133:14600)
	at MessagePortMain.<anonymous> (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:213:6789)
	at MessagePortMain.emit (node:events:519:28)
	at MessagePortMain.emit (node:domain:488:12)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2619) Subprocess xcrun simctl list runtimes --json execution resulted in an error:
2025-01-13 06:20:46.018 [error] Error: Command failed with ENAMETOOLONG: xcrun simctl list runtimes --json
spawn ENAMETOOLONG
    at ux (https://file+.vscode-resource.vscode-cdn.net/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/webview.js:1583:20981) [WEBVIEW LOG] Uncaught promise rejection
2025-01-13 06:20:46.019 [error] [WEBVIEW LOG] Uncaught exception Error: Command failed with ENAMETOOLONG: xcrun simctl list runtimes --json
spawn ENAMETOOLONG
    at ux (https://file+.vscode-resource.vscode-cdn.net/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/webview.js:1583:20981)
2025-01-13 06:20:46.209 [error] Error: Command failed with ENAMETOOLONG: xcrun simctl --set /Users/ian/Library/Caches/com.swmansion.radon-ide/Devices/iOS list devices --json
spawn ENAMETOOLONG
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:776:9)
	at A5 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:14:9974)
	at St (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:139:2548)
	at oy (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:13770)
	at sy (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:13975)
	at R9.loadDevicesInternal (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:16410)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5) Subprocess xcrun simctl --set /Users/ian/Library/Caches/com.swmansion.radon-ide/Devices/iOS list devices --json execution resulted in an error:
2025-01-13 06:20:46.210 [error] Error: Command failed with ENAMETOOLONG: xcrun simctl --set /Users/ian/Library/Caches/com.swmansion.react-native-ide/Devices/iOS list devices --json
spawn ENAMETOOLONG
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:776:9)
	at A5 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:14:9974)
	at St (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:139:2548)
	at oy (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:13770)
	at sy (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:14000)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Promise.all (index 1)
	at async R9.loadDevicesInternal (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:16496) Subprocess xcrun simctl --set /Users/ian/Library/Caches/com.swmansion.react-native-ide/Devices/iOS list devices --json execution resulted in an error:
2025-01-13 06:20:46.210 [error] Error: Command failed with ENAMETOOLONG: xcrun simctl list runtimes --json
spawn ENAMETOOLONG
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:776:9)
	at A5 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:14:9974)
	at St (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:139:2548)
	at P9 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:7616)
	at sy (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:14050)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Promise.all (index 1)
	at async R9.loadDevicesInternal (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:16496) Subprocess xcrun simctl list runtimes --json execution resulted in an error:
2025-01-13 06:20:46.210 [error] Error: Command failed with ENAMETOOLONG: xcrun simctl list runtimes --json
spawn ENAMETOOLONG
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:776:9)
	at A5 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:14:9974)
	at St (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:139:2548)
	at P9 (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:7616)
	at sy (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:14050)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Promise.all (index 1)
	at async R9.loadDevicesInternal (/Users/ian/.cursor/extensions/swmansion.react-native-ide-1.1.0/dist/extension.js:159:16496) Error fetching simulators


```

**Environment**

- Version of currently used Radon IDE (Extensions tab -> click on Radon IDE extension -> version is located next to the extension name) 1.1.0
- Version of React Native/Expo used in the project.
-     "expo": "~52.0.25",
-     "react-native": "0.76.6",
- Any other versions of tools related to the problem. CURSOR IDE

### PR DESCRIPTION
**Pull request by maciekstosio**
Fixes #896 

This PR solves the problem of IDE not being able to obtain $PATH when something is printed at the launch of the shell, by adding unique tokens before and after  `$PATH` value. This way we make sure only $PATH is extracted. 

### How Has This Been Tested: 

- add `echo "SOMETHING"` to your `./zshrc` 
- IDE should be able to obtain $PATH anyway

### CODE REVIEW

File: packages/vscode-extension/src/utilities/subprocess.ts [hunk 1]
```diff
@@ -16,8 +18,8 @@ async function getPathEnv(appRoot: string) {
 
   // Fish, bash, and zsh all support -i and -c flags.
   const shellPath = process.env.SHELL ?? "/bin/zsh";
-  const { stdout: path } = await execa(shellPath, ["-i", "-c", `cd "${appRoot}" && echo "$PATH"`]);
-  return path.trim();
+  const { stdout: path } = await execa(shellPath, ["-i", "-c", `cd "${appRoot}" && echo "${PRE_PATH_TOKEN}$PATH"`]);
```
Comment (kmagiera) [inline packages/vscode-extension/src/utilities/subprocess.ts:21]: I'd suggest that to make it easier to debug such problems in the future we should add log statement to print the output of this command

File: packages/vscode-extension/src/utilities/subprocess.ts [hunk 2]
```diff
@@ -16,8 +18,8 @@ async function getPathEnv(appRoot: string) {
...
+  return path.split(PRE_PATH_TOKEN)[1].trim();
```
Comment (kmagiera) [inline packages/vscode-extension/src/utilities/subprocess.ts:22]: would it be possible for the shell to also add something after the command? For example, there are some extensions that print exit code after each command. Maybe we should have both prefix and suffix to extract the path?

File: packages/vscode-extension/src/utilities/subprocess.ts [hunk 3]
```diff
@@ -5,6 +5,8 @@ import { Platform } from "./platform";
 
 export type ChildProcess = ExecaChildProcess<string>;
 
+const PRE_PATH_TOKEN = "{RNIDE_PRE_PATH}";
```
Comment (kmagiera) [inline packages/vscode-extension/src/utilities/subprocess.ts:8]: it is no longer "PRE". Can we just name it RNIDE_PATH_DELIMITER. Perhaps we can also just define it in the method as it isn't really used outside of it

File: packages/vscode-extension/src/utilities/subprocess.ts [hunk 4]
```diff
@@ -16,8 +18,12 @@ async function getPathEnv(appRoot: string) {
 
   // Fish, bash, and zsh all support -i and -c flags.
   const shellPath = process.env.SHELL ?? "/bin/zsh";
-  const { stdout: path } = await execa(shellPath, ["-i", "-c", `cd "${appRoot}" && echo "$PATH"`]);
-  return path.trim();
+  const { stdout: path } = await execa(shellPath, [
```
Comment (kmagiera) [inline packages/vscode-extension/src/utilities/subprocess.ts:21]: we can just operate on `stdout` here. Aliasing `stdout` to `path` no longer makes sense given we now the stdout may contain more than just the path

**Review by kmagiera — APPROVED** [review]
Left more comments inline
