### PR TITLE
Fix shift not working

### LINKED ISSUE #1116: SHIFT key inside simulator
**Description**
When using my laptops keyboard, I was unable to use SHIFT key inside simulator.
E.g.
When typing in email address for login, I use `SHIFT+2` for '@', but the key sent to simulator was just '2'. This works as expected when using iOS simulator without RadonIDE.

**Environment(Device/Simulator)**
- OS: MacOS 15.3.1 (24D70)
- Device: Macbook Pro M4
- Simulator Device: iPhone 15 Pro
- Simulator OS: iOS 18.4

**Environment(Packages)**
- Radon IDE: 1.5.0
- expo: "~52.0.42"
- react-native: "0.76.9"

**Environment(VSCode)**
- Version: 1.99.3 (Universal)
- Commit: 17baf841131aa23349f217ca7c570c76ee87b957
- Date: 2025-04-15T23:18:46.076Z
- Electron: 34.3.2
- ElectronBuildId: 11161073
- Chromium: 132.0.6834.210
- Node.js: 20.18.3
- V8: 13.2.152.41-electron.0
- OS: Darwin arm64 24.3.0

On a side node, thank you so much for this project. It's really convenient.

### PR DESCRIPTION
**Pull request by filip131311**
This PR uses a new api provided by sim-server in this [PR](https://github.com/software-mansion-labs/simulator-server/pull/228), to set up keyboard on iOS after the application is running. 

Fixes #1116

### How Has This Been Tested: 

- Run `expo-53` test app add text input and test shift functionality 
-  test shift after reloading the application

### CODE REVIEW

File: packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts [hunk 1]
```diff
@@ -245,6 +245,12 @@ export class AndroidEmulatorDevice extends DeviceBase {
     return promise;
   }
 
+  public setUpKeyboard() {
+    Logger.log(
+      "Keyboard setup requested. Keyboard setup is not required on on Android Emulator devices."
```
Comment (kacperkapusciak) [inline packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts]:
```suggestion
      "Keyboard setup requested. Keyboard setup is not required on Android Emulator devices."
```

Comment (kacperkapusciak) [reply packages/vscode-extension/src/devices/AndroidEmulatorDevice.ts]: debatable whether we need this log at all

**Review by kacperkapusciak — APPROVED** [review]
