### PR TITLE
Fix IDE panel relocation after selecting preview/storybook

### LINKED ISSUE #761: IDE panel relocates to right tab after selecting preview/story
After selecting a preview or story with the Radon IDE panel open on the left editor tab, the IDE shifts to the right tab.

https://github.com/user-attachments/assets/86211141-f8ee-402a-9e65-74681227771e

**Environment**

- Radon: v0.0.23
- expo-router (from test-apps)

### PR DESCRIPTION
**Pull request by p-malecki**
This PR resolves the issue where selecting a codeLens with a preview or Storybook's preview unintentionally relocates the IDE panel to the editor column to the side of the active one (`ViewColumn.Beside`). The `showIDEPanel` function has been fixed to ensure that the IDE panel remains in the active column, labeled with our IDE's name.

Fixes #761

### How Has This Been Tested:
- The IDE was opened in the left tab and code with a preview in the right tab. After selecting the codeLens, it was confirmed that the IDE remained in its original position.

|Before|After|
|-|-|
|<video src="https://github.com/user-attachments/assets/86211141-f8ee-402a-9e65-74681227771e" />|<video src="https://github.com/user-attachments/assets/bdeb37cf-8130-45c9-988d-1c85abb7f75d" />|

### CODE REVIEW

File: packages/vscode-extension/src/panels/Tabpanel.ts [hunk 1]
```diff
@@ -60,7 +60,11 @@ export class TabPanel implements Disposable {
   public static render(context: ExtensionContext, fileName?: string, lineNumber?: number) {
     if (TabPanel.currentPanel) {
       // If the webview panel already exists reveal it
-      TabPanel.currentPanel._panel.reveal(ViewColumn.Beside);
+      const activeRNIDEColumn = window.tabGroups.all.find(
+        (group) =>
+          group.activeTab?.label === "React Native IDE" || group.activeTab?.label === "Radon IDE"
+      )?.viewColumn;
+      TabPanel.currentPanel._panel.reveal(activeRNIDEColumn);
```
Comment (maciekstosio) [inline packages/vscode-extension/src/panels/Tabpanel.ts:67]: What if `activeRNIDEColumn` will be null? Maybe we should throw an error or warning.

**Review by maciekstosio — CHANGES_REQUESTED** [review]

File: packages/vscode-extension/src/panels/Tabpanel.ts (hunk 1 above)
Comment (p-malecki) [reply packages/vscode-extension/src/panels/Tabpanel.ts:68]: Instead of throwing an error lets simply use ViewColumn.Beside when activeRNIDEColumn is null

File: packages/vscode-extension/src/panels/Tabpanel.ts [hunk 2]
```diff
@@ -60,7 +60,12 @@ export class TabPanel implements Disposable {
   public static render(context: ExtensionContext, fileName?: string, lineNumber?: number) {
     if (TabPanel.currentPanel) {
       // If the webview panel already exists reveal it
-      TabPanel.currentPanel._panel.reveal(ViewColumn.Beside);
+      const activeRNIDEColumn =
+        window.tabGroups.all.find(
+          (group) =>
+            group.activeTab?.label === "React Native IDE" || group.activeTab?.label === "Radon IDE"
+        )?.viewColumn ?? ViewColumn.Beside;
+      TabPanel.currentPanel._panel.reveal(activeRNIDEColumn);
```
Comment (kmagiera) [inline packages/vscode-extension/src/panels/Tabpanel.ts:68]:
```suggestion
      TabPanel.currentPanel._panel.reveal();
```

**Review by kmagiera — APPROVED** [review]

**Review by maciekstosio — APPROVED** [review]
