### PR TITLE
fix: device appearance on ios

### LINKED ISSUE #1528: Dark/Light mode doesn't work on iOS
**Description**  
Changing the device appearance (light/dark mode) does not update in real time on iOS.  
After rebooting, the device starts with the selected mode.  
On Android, this works correctly.  

**Environment**  
- Radon version: 1.11.1  
- OS: iOS 18.5

https://github.com/user-attachments/assets/94049605-ca56-4e79-b715-ab279e547b91

### PR DESCRIPTION
**Pull request by filip131311**
Fixes #1528

After #1475 we started noticing that light/dark mode change is not working on ios devices. This is because after `com.apple.cfprefsd.xpc.daemon` restart `com.apple.SpringBoard` stops working properly. To adres that we jst restart the SpringBoard process. 

### How Has This Been Tested: 

- run  `expo-54` test app and perform all kinds of reloads 
- test appearance settings after each one 
- turn of radon and do the same

### How Has This Change Been Documented:

internal

### CODE REVIEW

File: packages/vscode-extension/src/devices/IosSimulatorDevice.ts [hunk 1]
```diff
@@ -343,6 +343,24 @@ export class IosSimulatorDevice extends DeviceBase {
     } catch (e) {
       // ignore errors here and hope for the best
     }
+    try {
+      // After performing the above hack we need to restart SpringBoard as well,
+      // because com.apple.cfprefsd.xpc.daemon restart breaks it's ability to read
+      // the preferences (e.g appearance).
```
Comment (filip131311) [inline packages/vscode-extension/src/devices/IosSimulatorDevice.ts]:
```suggestion
      // the settings (e.g appearance).
```

File: packages/vscode-extension/src/devices/IosSimulatorDevice.ts [hunk 2]
```diff
@@ -343,6 +343,24 @@ export class IosSimulatorDevice extends DeviceBase {
     } catch (e) {
       // ignore errors here and hope for the best
     }
+    try {
+      // After performing the above hack we need to restart SpringBoard as well,
+      // because com.apple.cfprefsd.xpc.daemon restart breaks it's ability to read
+      // the settings (e.g appearance).
```
Comment (kmagiera) [inline packages/vscode-extension/src/devices/IosSimulatorDevice.ts]:
```suggestion
      // Restarting cfprefsd breaks the SpringBoard process which in particular controls things like
      // the appearance settings. We need to restart it following the cfprefsd reset.
```

We should not use 'hack' here as the word itself has negative association and also it isn't really a hack in its most common usage.

File: packages/vscode-extension/src/devices/IosSimulatorDevice.ts [hunk 3]
```diff
@@ -343,6 +343,24 @@ export class IosSimulatorDevice extends DeviceBase {
...
+        "--set",
+        deviceSetLocation,
+        "spawn",
+        this.deviceUDID,
+        "launchctl",
+        "kickstart",
+        "-k",
+        "system/com.apple.SpringBoard",
+      ]);
+    } catch (e) {
```
Comment (kmagiera) [inline packages/vscode-extension/src/devices/IosSimulatorDevice.ts]: I recently found out that we can just pass `reject: false` as option to exec. This results in the possible errors not being thown while we'd still get the errors reported in the logs. In may be cleaner to use it here and in the above calls as well.

**Review by kmagiera — APPROVED** [review]
Looks good, left some small comments inline

File: packages/vscode-extension/src/devices/IosSimulatorDevice.ts (hunk 3 above)
Comment (filip131311) [reply packages/vscode-extension/src/devices/IosSimulatorDevice.ts]: thanks, that's good to know
