### PR TITLE
Fix gap in split lines of dimensions in InspectDataMenu

### LINKED ISSUE #861: Gap in split lines of dimensions in InspectDataMenu
**Description**
In the InspectDataMenu, dimensions display with a large gap between lines on a narrow window.

Screenshot 2024-12-18 at 01 02 22

**Environment**

- Radon: v1.1.0.rc0

### PR DESCRIPTION
**Pull request by p-malecki**
This PR addresses a gap in the split lines of dimensions in the InspectDataMenu by removing space characters from the displayDimensionsText and reducing the line-height.

Fixes #861 

### Screenshots:
|Before|After|
|-|-|
|Screenshot 2025-01-10 at 10 39 01|Screenshot 2025-01-10 at 10 38 44|

### CODE REVIEW

**Review by filip131311 — APPROVED** [review]
LGTM

File: packages/vscode-extension/src/webview/components/InspectDataMenu.tsx [hunk 1]
```diff
@@ -65,7 +65,7 @@ export function InspectDataMenu({
       const topComponentHeight = parseFloat((frame.height * device.screenHeight).toFixed(2));
 
       if (topComponentWidth && topComponentHeight) {
-        return `Dimensions: ${topComponentWidth} × ${topComponentHeight}`;
+        return `Dimensions: ${topComponentWidth}×${topComponentHeight}`;
```
Comment (kmagiera) [inline packages/vscode-extension/src/webview/components/InspectDataMenu.tsx:68]: shouldn't we just use `&nbsp;` to keep the space but avoid line breaking?

**Review by kmagiera — APPROVED** [review]
